---
title: "伦理和道德是推理和演绎"
author: "Zhaose"
date: "2026-09-19"
categories: [meditationes]
---

## 基本论述

伦理和道德，很多时候被看作是哲学的直接应用所得出的结果。而现实当中，伦理和道德，或多或少都被传统所决定。其实这当中已经发生了矛盾，因为任何哪怕强调传统的伦理和道德都想要从他们认同的哲学当中去寻找来源与正当性，因为他们知道传统本身不具有正当性。中国传统的伦理总想从儒家哲学当中去寻找正当性，西方则跑到基督教哲学当中去寻找。然而这些哲学体系在我看来，都假设了太多不合理，人们根本不知道也无从知道的东西。自大的哲学当中得出自大的道德和伦理，以此来给予了人们多余的教育和限制。一个合适的道德和伦理，必然要从现代的，谦虚的哲学当中来，而这样的哲学体系大概有很多。不过，在我看来得出的伦理和道德，至少在基本的层面，不会差得太多，因为哪怕不同的哲学有不同的方法和基础，表现在对一个高度现实的问题研究上时（伦理和道德），通常会展现出相同或相似的结果。

在此，我以我所以为的一些基本的假设，或者说是公则，这些大多是直明的。而从这些基本当中，辅以理性的方法和适当的其它假设或简化，来对常见的伦理和道德进行一些推断，并反驳一些谬误。当然，我不希望人们以数学的标准看待下面的论证，因为他们不够严密；但他们如物理学一般，足够实用，就如同分析房梁是否会断裂，用实用的材料力学分析（它不是物理学的终极真理），比烧龟甲占卜，要有用得多。

- **设定一**：人为自己的选择负责，而不为不是自己所选择的负责。
- **设定二**：人没有主动选择要成为道德意义上的人，但人都是道德意义上的人。
- **设定三**：人可以一定程度上互相理解，哪怕不能完全互相理解，而这是由于人有理性所得出的必然结果。
- **设定四**：人的感受具有真实性，但人的感受只有作用在发生于自身的事情上时，方才有道德和伦理上的效力。
- **设定五**：多余的限制是错误的限制。

## 引理

下面我们就利用这些来检验一些现实当中受到认可的伦理，和一些有争议的道德或者伦理，并推得一些引理。

### 引理一：人不会为任何一件事负全部责任

根据设定二，人没有选择成为道德意义上的人，因此根据设定一人不为自己作为道德的人负责，因此人也不可能为某一件事负全部责任。这是说，任何事当中如果要追究责任，则必然有其本人之外的责任存在，如周围环境的责任。

### 引理二：更广泛的道德标准更正确

人无法选择自己的大多数事情，如自己所处的环境，自己所出生的身体，等等。我们很难说人作为一个整体有多少是完全出于自身选择的，因此一个更广泛的标准更能减少其受设定一的质疑，便更具正确性。

### 引理三：道德不迎合公共感情

根据设定三，人可以互相理解。根据设定四，只有人们在相互理解并代入之为当事人时，这种情感方有效。因此「看起来不舒服」没有道德效力，除非是「我如果是当事人我会觉得不舒服」。因此要分析自己以外的事，这正是道德（一个普遍的东西）所做的，不能依赖简单的感情先入，而必须依赖理性的推理先代入，方能以受事者角度感觉。而理性不是公共感情，因此道德跟公共感情无关。

## 验证

### 验证一：偷窃是错误的

根据引理一，我们当然不能说偷窃完全是一人之过，但是根据设定四，和设定三，任何一个人被偷窃时都会感到不快，而偷窃又有大量的自我选择在其中。因此我们可以自信地说偷窃是错误的或者说偷窃之人要担责，而只是其和社会环境之间的责任分配多少的问题。

### 验证二：已所不欲勿施于人

根据设定三和四可得。或者根据引理二，也可得出。事实上其和引理二是类似的。

### 验证三：我们应当谦虚待人

根据引理一，人不会为任何的事负全责，因此任何有瑕疵的人，都并不会是其完全本身的过失所引起。另外根据设定三和四，人们都喜欢被谦虚相待，故正确。

## 谬误

### 谬误零：有些道德标准难以完全实现，因此沒有意义

甚至不用动用我们的设定。假如此为真，则虽然人们说「不应盗窃」，「不应杀人」，但世界上总有人会盗窃或杀人，因此人们不盗窃不杀人没有意义。荒谬至极。

### 谬误一：男性应当爱上女性，而女性应当爱上男性

对这一谬误，想要论证它正确的人通常会从「自然设计」，「天生的使命」方面来论证。而人没有选择成为生理上的男性或者生理意义上的女性。因此，如果一个说法要求某个性别去喜欢另外一个性别，则其无异于要求人为自己无法选择的生理性别担责，而这正与我们的设定一相悖。

另外，我们也可以从引理二来直接得出结论。

当然，在现代我们面临远超单纯生理性别外的问题。如果一个人是决定自己要成为男性，那我要求它要喜欢女性呢？那也很奇怪了，如果生理意义上的要求本身已没有效力，那么这样的要求根基何在。于是它便成为了多余的限制，根据设定五，其是错误的。至于什么「公众反对」的说法，根据引理三，已经明白。

### 谬误二：人应当感谢他们的父母，只因他们的父母生育了他们。

人出生不是自己的选择，因此人不为自己出生这一件事实负责。如果父母没有做出其它值得子女感谢的事情，则子女就无责任感谢他们。而父母选择了生出子女，因此父母对子女才有养育的责任。当然，如果是社会强迫父母生育，则环境也有责任，正如我们引理一所说，父母不是负全部责任，但其负的责任必然比对此不负责的子女要更多。

同样的，人应当感谢他们的国家也不通，因为多数情况下人不能选择自己出生在哪个国家（设定一）。而即然对多数人来说这一说法都不通，那他对于移民来说也是多余的（设定五），更何况加入本身就是一个契约性质的行动。因此人对于国家，无论是天生的公民还是自愿加入的，与国家之间都是契约，也只能是契约的关系。

### 谬误三：道德没有意义，因为其受文化的制约。

根据设定三，人具有互相理解的潜力，因此人完全可以一定程度上想象其它境遇或是文化的人所遭遇的，并且这是由于人有实践的理性所必然得出的。如此而言，我们至少可以在一定程度上比较不同文化的境遇。而我这篇文章所讨论的所有问题，从设定开始，我便不认为他们是受文化制约的，因为他们如此简单，完全没有达到触及复杂文化的地步，如果有文化与之相扺，我只能说是文化错了。

并且不同文化如果对不同人施以不同的限制，那也是错误的。因为大部分人无法选择自己出生在什么文化当中，如果使用不同文化不同道德，那无异于说人要为自己出生的文化负责，根据设定一，谬误。

### 谬误四：不够努力是所有困境的唯一原因

原因即是责任。根据引理一，直接得出其是错误的。

### 谬误五：人应当以繁衍后代为自己的责任

繁衍后代需要男性和女性的配合，并且在这个配合当中，男性和女性因生理承担了不同的责任。如果繁衍是责任，根据设定一，其和谬误一同样错误。

那么如果我们的科技进步到了足以让人类的繁衍脱离女性和男性肉体的程度，比如完全的人造子宫呢？这自然会给这一责任认定更大的正当性，但是我想不出为什么这种责任认定是必要的，人类是否繁衍在事实上不伤害任何人，我们也没有道理强加给我们的后代继承我们文明或者背负我们养老的责任。因此这是也是一个被设定五否定的谬误。