---
title: "序"
author: "Zhaose"
date: "2026-04-30"
categories: [meditationes]
---

哲学是一个听起来颇为高深的词。然而，世界上所有学问只有在不了解的时候才听起来高深，这种“了解”不一定是深入的学习和应用，也可能只是泛泛地接触和熏陶。就像物理学、数学，人们当然认为它们高深，但它们听起来并不高深，之所以如此不过是因为在现代的生活和教育当中，数学和物理相关的知识过于重要，使它们带上了世俗生活的色彩。每个人都会学习算数，每个人也都在中学学习物理学，化学等等自然科学；但是哲学、伦理学、逻辑学这些词几乎还是只会在大人物生平中听到。我想它们也许并没那么高深，如果一个人有能力去学会自然科学的知识，那他应当也有了用于思考哲学的理性。

但是我根本没系统学过哲学，而自己的胡思乱想被称作哲学也不太合适。但是如果肆无忌惮一点，和物理学等等不同，什么都可以被称作是“哲学”。整天在大众杂志（如《读者》）上那样的文章对生活中的所有东西都触摸一番，然后总结出某种“生活哲学”，我实在是觉得只是无聊地博人眼球。然而如果它们都能称作哲学，那我想我可能比他们的作者要强一点。我也许写不出华丽吸睛的文字，但应该比他们更有理性的思考一点，也更有支持特立独行的想法的固执。所以我觉得至少我可以大胆写一些具有“哲学色彩”的东西，既可以让我真的做一些思考，又不像学习和运用物理知识或其它自然科学那样谨小慎微，生怕出了哪怕一点小错误。故而我认为我写的这些东西算不上哲学，最多是“哲学色彩”的思考、想法。另外也是归功于最近开始读一些哲学著作，让我对如何表现这些想法有了一个大概的样本和标准。

## 对哲学作为学科的印象和与其它学科的异同

现代的学科更多的是一种知识体系，并尝试用这个知识体系来探索和解决问题。各个学科最根本的不同就是它们的知识体系不同，因而作为它们知识体系最基础的本体也不同，进而导致它们所被用来探索和解决的问题不同。当然也可以说是学科的体系是围绕要探索的问题建造的，但这两个哪个是鸡哪个是蛋并不太重要。

各个学科当中，数学让我觉得它没有一个明确的要探索的问题，它淡化了问题的存在而注重探索本身。探索本身就是运用逻辑和推理，从已知的当中推出未知的。而数学有很多分支，探索看起来截然不同的东西，看起来也没有一个统一的为了什么而探索的目的，更证实了它主要就是探索本身。数论上的皇冠应该是哥德巴赫猜想、费马大定理、及诸如此类的难解问题，但人们会认为这些问题是数学学科的“核心问题”吗？在数论之外的其它分支也有它们的不同问题，但这些问题从更大的视角上看来有些细支末节，不像是一个统一的本质问题，如果说它们有一个统一的问题，那只能是探索人类认知的边界，而那本身就是探索了。这种探索是完全在理性的范围内完结的推理，不同的前提条件唯一地催生出不同的结论，因而我们很难说哪一个数学分支更加基础，更加根本，更加接近唯一完美的真理。也许数学并不应该算作一门学科，而应该拆分来看，但它们沿着具体核心问题前进的色彩仍然称不上浓厚。

其它的自然科学学科与数学便有了本质上的不同。物理学的终级目标是具体的，为了解释和预测物质世界的运行、化学的目标是解释和预测物质在比原子更广层面，但又微观的尺度下的相互作用、生物学解释和预测被人们称为有生命的物质、自然地理学和气象学解释和预测地球上所发生的宏观现象。社会和人文科学也是如此，不过从研究和预测自然相关的现象变成了研究和预测人类组成的复杂系统相关的现象。

因此，在我看来，作为一门学科，哲学其实相比较于数学更接近其它学科。因为哲学有比较公认的，尝试解决的问题，比如人类的意识，思想，感知，等等。哲学作为一个概念，或者一个知识体系，应当是更接近数学，因为和数学一样，哲学所有的思考都可以在纯粹理性范围内完成，而其它的科学都不得不依赖实验。但是作为学科，哲学有明确的目标，这使它脱去了数学的游离感。而哲学作为学科最相近的是物理学。因为每个学科当中，最根本最基础的知识就算是本学科独有的，其在研究中，除了物理学（它不依赖数学和哲学之外的其它），都不得不借助完全在自己研究和预测目标之外的其它规则。换而言之，如果我们把人类的理性看作是根本的，那数学和哲学是最根本的学问，而在这之上是物理学，之后才是其它的学问，他们之间相互引用，相互依赖，并且都依赖物理学、数学、哲学。而数学学科不注重问题，物理学学科则在有明确的问题的基础上不断地寻找能够更加完美解释问题的理论，并且这个理论是完全在物理学框架之内的，某种程度上是最初的，最完备的，最根本的理论（假设的集合）。因此，在哲学学科在自己的框架之内，寻找最根本的本体，最根本的方法，最根本的知识，来解释哲学学科的问题，这使得哲学更接近物理学，最终的目标是在自我的体系内完整地解释核心的问题。

于是，哲学是和数学平等的学问，但类似物理学的学科。

## 一种现代流行大众“哲学”中的谬误

这也是我不写不快的根本原因。哪怕我所说的都称不上真，下面我要批评的东西也绝不会是真。它们如此谬误，以致于我想哪怕我说得不对，也会有其它的理论来反驳它们。不过我的说辞也许可以起到某种作用，同时也是我自己对抗这些思潮的工具。

相比于古代，现代的科学发达得令人惊叹。从前人们一直都接受宗教或者礼教的灌输，现在则会被额外地灌输一些科学概念。如果一个人不肯运用他的理性去思考和评判自己所受到的灌输，就没法形成自己的哲学，而只能机械地记忆和复述外界的命题，把它们强行套用在自己所遇到的问题之上。在从前，这是狂热的教徒、顽固的保守分子，现在则有多出了一个以科学为由称道虚无的选项。他们的论证往往很简单：我们有了一个不错的科学体系，这个科学体系似乎没有它完全不能解决的事情，如果有，那等它日后完善也必定可以解决，这是论证的根本，而且事实上，我也基本上同意这种看法。但是他们的下一步就跳跃为，我们人类的大脑也是由物质构成的，而物质的运动是可以用科学预测的，我们同时还认为意志、理性、感知，都产生于大脑，因此这些东西也都不存在，它们只是物质运动规律的某种表象。这个说法不太有道理，因为我们知道一个系统的特性往往不能完全地用组成其部分的特性来完全描述，必须加上它们之间的相互作用，而且必须完全地，确定地，研究每一个部分和其它所有部分之间的相互作用，才能完成能从部分到整体的完全推进。电脑芯片是由硅晶体制造的，当中流过电流，而我们在电脑上进行编程，进行输入和输出，我们会说编程电脑的本质是电子在硅晶体中运动吗？

哦，事实上这么说没有错，因为我们在设计电脑的时候就无微不至地研究了晶片的所有部分，所有二极管，并且以我们有理解的方式把他们连接起来，电脑这个系统我们可以说是完全明白，完全理解的。但是我们在这些硅和其中运动的电子之上，构造了一个完全不相同的，具有我们从硅和电子本身完全看不出的功能的实体。硅和运动的电子是“真”，而可编程可运作的“图灵完备”也是真。图灵完备似乎以低层的硅和电子为载体，但作为概念已独立存在。至于人类的大脑，人类甚至都还没能完全地分析其中所有的联系，又怎么能断言理性不存在呢？哪怕完全地分析了，又如何能证明理性不存在呢？这无非是来自于粗浅的科学观念的想当然，本身都算不上是科学，更算不上是“对理性、意识、感知的现代哲学理解”。

再者，如果我们相信现有的科学法则，我们不得不思考科学法则从何而来，依赖什么确立了它的法则地位。科学，或者说我们现在讨论的自然科学，是实证的学科，即通过实验来证明，通过理性来归纳，将原本归于广延的事物抽象纳入到思想实体中。如果这样，我们就无法拿科学来证明理性的不存在，不然科学就是无根之木。哪怕任何人不认同这一命题，他们也不得不承认，实验的过程是依赖于感知的，如果大脑是机械的，理性不存在，但感知却存在，那是什么来解释和串联感知呢？从这个方面思考，也得不到直明的结果。因此，粗浅的还原论是站不住脚的。

## 多思考，多沉思，而不是假装思考

上面是一个例子，而我想说明的是，哲学不是说从某个现象当中看到了一个因果链条，或者听说了一个因果链条，而用它来指导思考或者行动就成了哲学。那只不过是囫囵吞枣、不加思索或者假装思索。观察到的因果链条如果当中有不直明的环节，那它就也许不真，它可以作为一种生活指导，但算不上哲学。而如果它让对自己的理性产生了怀疑，那更应当去仔细思考那是不是存在一个真的这么颠覆性，而又如此简单的理论。事实上，如果我们仔细地分析，那些“生活哲学”不过是对因果表象的机械重复，而试图从前所未有的简单角度来解决哲学终级问题的主张，则不过是拒绝运用理性，急不可耐地为自己不那么感兴趣的问题画上讨论的句号，殊不知这样的懒惰在自己运用心智认识世界，指导行为的时候，后患无穷。

总结来说，现在的人们连半点具有哲学色彩的思考都不愿进行，却大谈特谈各种“哲学”，还将一些博人眼球的谬论视作简单的，超越“脱离现实的学究气”的真理，实在是引人担忧。