---
title: "物质与心灵、真理与所谓之上帝、以及其它种种"
author: "Zhaose"
date: "2026-07-14"
categories: [meditationes]
---

构建一种新的哲学想法在现代当然是几乎不可能的，毕竟历史上最聪明的人们早就就相关的问题想过太多，而哪怕并不谦虚地讲，我也并不觉得我能比得上他们半点。所以我所想的东西必定是矛盾百出的，与已有的东西几乎可以说肯定某些方面相似的，而杂糅拼凑而成的。虽然如此，但是正如我前面所说的，在我看来哲学是一个实践的学科，即解释已有现象占很大部分的学科，因此就好像物理学家们很多时候对百分百严格的数学推理没有那么在乎一样，我也将以此为由，偷一些懒，且不去深究后面的逻辑是否完全正确，而只求解释本身的自然、合理。

## 物质与心灵、一元论与二元论

很多人，尤其是受到理科教育或者某些理论浸染的人，往往称自己是唯物主义者；而相反的，相信宗教或者是某些古老迷信的人，则被别人称为是唯心主义者。就这样，物质和心灵被区分开看待，二者要么蹩脚地去用明明机械的物质解释似乎不机械的心灵而对人的主观性和行为的解释起不到任何作用，要么去把物质作为某种更高存在给予的幻象，成了一种自大的盲信的理论。事实上，在我看来，不管是物质还是心灵，看到的东西，也许事实上也存在的东西，以及情感，话语，思绪，无不都可以用一个词来形容，即「现象」。而所有现象当中，最明确的自然是笛卡尔所说的「我思故我在」。至于哲学是要去做什么，无非是给予这些现象一种解释，并提出一套自洽地可以用某些现象预测其它现象的理论，就好像物理学所做的一样。也就是说，心灵和物质之分其实不过是现象的明确程度上人为强加的分类。心灵是我们好像内在就能感受到的现象，而物质似乎是要由某种外界刺激才能感受到，所以心灵的现象好像更明确；但是心灵的现象则很多时候不太稳定，混沌而无迹可寻，物质的现象则似乎更加容易理解和推测。但是既然都是某种方式呈现在我面前的，它们这些现象之间就没有本质的区别。但是「我」似乎是一种心灵的实体，那这岂不又是一种「唯心主义」了？这就如我之前所说，我思故我在也是一种现象，它把我呈现在了我自己面前，它并非根本，其它东西也不由它而来，只是说它是最明确的现象，就好像在地球上一个物体会往下掉是物理学中最明确的现象之一。如果任何理论不能解释为什么东西往下掉，哪它就不是完整的理论，但不是说我们从东西往下掉来推出所有其它事情。这也是我为什么说物理学的研究方法很重要，即我们处于一个解释的角度，而不是经验外推的角度。这样我们就可以自信地说，这并非唯物主义也并非唯心主义，当然也并非二元论，因为物和心根本就不是元，要说的话可能可以说是「中立一元论」，即我们的解释是元，而心灵，物质，都是这个解释所给出和要解释，要预测的现象。

通过这样的设定，我们可以看到所有的唯物和唯心的问题都解决了，因为我们不再把不根本的东西视为根本的。我们不必困扰为什么机械的物质能制造出看似不那么机械的心灵，而不得不把心灵也说成是机械的，因为心灵是现象而物质也是现象，我们可以有一个理论同时解释二者，哪怕心灵真的是机械的或者不是，那是这个理论的问题而跟所谓物质不再有关系。同样的我们也谦虚地放下自己作为中心的想法，虽然我感受现象，现象也呈现在我面前，但我也是现象本身，因此我也不可能是根本的，故而也不会自大地把自己认为在物质之上。事实上达成这样的想法非常简单，只要不妄自菲薄，也不自诩为最大，就自然会发现这才是最合理的想法。

## 真理与所谓之上帝

什么是真理呢？真理是能够解释现象的理论，真理也许会有它的适用范围，它可能能解释一些现象而不能解释另一些，而大部分的真理则都是这样。也就是说，大部分的真理都是部分的。部分要从整体中来，这个想法也很好理解，而且如果我们想象对所有部分的真理做一个列举，然后当我们看到一个现象的时候，根据这个现象去选择某一个理论成功地解释，那这一个由所有不完全的真理和这一套选择树所构成的理论，自然就成了完全的真理。当然有人可能会说如果我们分了不必要的类，把某两个可以统一的东西没有统一解释，那这样的理论是不完全的。我不这么认为，这只能说这样的理论不是最优美的，但在功能上如果没有问题，那它就也没有问题，当然这也不妨碍我们应该去寻找和偏爱更优美更自然的理论。因此我们对真理是不是完全或者是不是真理只考虑它的「实用性」而不考虑主观上的「优美性」，故而真理肯定是存在的，因为如果我把适用范围限定到最小，那么结果就必然显而易见，而这个最小的真理也是真理。同时完全的真理也是必定存在的，因为把所有最小的真理统一在一起，哪怕不优美，它也完全。

下面的重要的一点就是，按这样的说法有人会说，那这个完全的真理不就是上帝吗？你怎么还自称是无神论者呢？这就不得不说什么是上帝，什么是优美的真理，而且在优美之外，所谓上帝，或者说有神论者所认为的从某本书中就能看到的人格化的上帝，为什么包含在真理中就会变成错误。

首先如果说，知晓一切的就是上帝，而上帝只是知晓一切，那完全的真理就是上帝。这没什么好说的，哪怕有人说上帝全能，其实完全的真理是上帝也没什么问题，因为在我看来全能无非是能解释所有现象。但是这些无非是一种浪漫化和对概念的重新命名，以试图把让某些人安心的毫无道理的想法粗劣地映射到此处的东西上来寻求安心。因此这样的说法没什么意思，通过某本书籍小说得到的东西也不应该被套到此处。

其次就是什么是优美的真理。更优美的真理自然是能统一地解释更多的东西的，并且没有多余的无用部分的，即统一原则与剃刀原则。统一原则其实不好考虑，因为有很大的模糊成分在，而剃刀原则就明确得多。一个人格化的上帝，且不说我们早已有对狭隘的全知全能全善的存在会引起悖论的明确证明，它也完全不是必要的，因为一个中性的理论理应完全可以解释所有现象。举例来说，人要善良，这本身可以是一种理论，而不必说某个全知全能全善的上帝说人要善良。后者不比前者能解释更多，还比前者多了个没用的部分。有人会说后者更统一因为有个上帝为所有负责，那我就改变一下说辞，完全的真理说人要善良，哪不也统一了吗？我们所说真理蕴含了它是完全真理一部分的先验假设，而某个全知全能全善的上帝并不能提供比这种最简单的统一性更大的统一性。所以说，强行加入全知全能全善的上帝的理论，是没有不考虑这样一个怪物的理论更加优美的。

再者真理必须是不能自相矛盾的，除非我们把两个部分的真理矛盾的部分限制在它们的适用范围之外。而一个试图解释所有的全知全能全善的存在无法被限定适用范围，因此所有它的矛盾都是不可避免的，因此所有前人发现过的悖论也是不可视之不见的。如果全善的存在全能为何世间还有邪恶而它不去除邪恶？如果全知的存在知道结果为何还要考验？与其去把这些乱七八糟的东西强行加入引出一个自相矛盾只能装傻来假装它是合理的理论，不如早早地把它扔掉。

因此，人格化的上帝对于哲学上来说，在理论的优美性上其不能增添分毫，更要命的是其反而会引入巨大的无法解决的矛盾，因此必须避免。

## 确定性、我之于真理、我理解世界

对于学习过自然科学的人来说，我们移除了人格化的上帝而把理论作为世界的根本，那就引发了一个问题，即「没有人投骰子了」。现代的量子力学已经明确地告诉我们，这个世界不是明确地决定论的。那如果一个理论只能预测说我去摸一只猫它有百分之五十的概率摸不到而有百分之五十的概率可以摸到，并且严格地说明无论我再知道更多的任何东西都没法做出更精确的预测了，那这个理论还能是完全的真理吗？一个完全的真理，怎么能够有所不能完全预测的，或者有包含不确定性的东西在其中呢？除了我们引入一个人来看着这个世界并且投投骰子，还有什么办法来解决呢？

这当中的问题不在于我们的真理出了问题，而在于我们对现象的理解陷入了一种狭隘的误区。摸到猫和没有摸到猫确实是现象，而百分之五十的可能性摸到猫剩下百分之五十摸不到，或者摸很多次猫有大概一半的次数摸到了，也是现象。前面我们也说到，人的心灵活动也都是现象，所以事实上我们已经明确了一点，即现象不是狭隘地确定的。现象可以是在时间尺度上的多个现象的集合作为整体被预测，也可以是作为某种可能性被预测。因为现象本身并不是什么最根本的东西，我们也没有必要去纠结必须要单次的确定的东西才是现象，这样的坚持不过是从前时代留下的偏见。所有被呈现的东西整体也都是一个现象。因而我们的完全真理只要能够解释整个大的现象，就足够认为它是完全的了。

因此，既然我们交叉比对了物理世界的不确定性，我想心灵上的不确定性本身也得到了一种正名。人是否有主观性，是否能做出决定，如果我们对机械的物质都不得不放弃狭隘的机械的理论，就更没有理由把其应用在心灵之上。虽然完全的随机性和主观性确有区别，但要反驳机械的心灵已经足够。因此人心灵的整体现象本身既然已经确切地呈现在我们面前，那就不要对其再扭扭捏捏了。当然，心灵作为现象，必然也是完全真理的一部分，应当能由完全真理推导出其存在，因而我可以说，我就是真理的一部分。我理解世界，也就是我试图去理解和接近完全真理本身，也就是扩充「我」在完全真理中所占有的部分。

## 再次声明研究方法、解释的视角、以及犯错

事实上，因为我上面所说的研究和思考的方法，多从自然科学的研究方法中借鉴而来，很大程度上是有些偷懒和不严谨的，但是我们对世界的根本看法，即完全真理的现象呈现在我们面前，除此之外没有其它确切的东西，给了我们极大的豁免，也给了我们所谓的错误某种价值，并且给了我们思考错误的指引。错误多种多样，但是无非是通过我们所掌握的，或者我们所相信的理论，与呈现在我面前的现象产生了偏差。哪怕只是因为我犯了一个粗心大意的错误，在某步计算中把二加三算成了六，那也是一样，因为我在那一刻认为二加三是六，而呈现给我的现象告诉我并非如此。粗心的错误多是暂时的，重新审视就可以修正，而如果是理论本身不够完备，比如牛顿力学之于相对论，那我们也不必感到灰心，就如前所说，我们发现了完全真理的一部分，但是这个一部分与呈现在我们面前的新现象不同了，这恰恰给了我们知晓更多部分的机会。虽然完全真理是本，而现象从完全真理上来，但我们本身的现象就使我们确定（当然这些现象同样也是由完全真理中来的，但因为我们处于解释的视角，呈现在我们面前的其它现象如果我们能解释或者能预测，那不管我们本身理性现象是什么，不去思考我们与一棵树，一块石头有什么区别，都无所谓）：我们需要通过现象来重现和接近完全的真理，不论是心灵的现象，理性的现象还是物质的现象。这一点适用于所有学科的研究，哲学考虑所有现象，数学考虑理性的现象，物理学和其它自然科学考虑物质的现象。如此我们可以看到，解释的视角不仅在学科研究上具有普适性，并且是一种积极的、灵活的、可以不断进步的研究方法。